name: Publish Package

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub App token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.LANSWEEPER_BOT_APP_ID }}
          private_key: ${{ secrets.LANSWEEPER_BOT_PRIVATE_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Configure Git
        run: |
          git config --local user.email "github-app@lansweeper.com"
          git config --local user.name "Lansweeper Deploy Bot"

      - name: Increment Version
        run: |
          npm version patch -m "Bump version to %s [skip ci]"
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Push Version Update
        run: |
          # Create a new branch for the version update
          git checkout -b version-update-${{ env.NEW_VERSION }}
          git push https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/Lansweeper-public/MCP-server-lansweeper.git HEAD:version-update-${{ env.NEW_VERSION }} --follow-tags

          # Create a pull request
          gh pr create \
            --title "Version update to ${{ env.NEW_VERSION }}" \
            --body "This pull request updates the version to ${{ env.NEW_VERSION }}." \
            --base main \
            --head version-update-${{ env.NEW_VERSION }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: yarn publish --access public --new-version ${{ env.NEW_VERSION }} --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
